name: Build and run tests

on:
  push:
    branches: [ main ]

env:
  GO_VERSION: 17.2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...
